# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hudes.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'hudes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhudes.proto\x12\x05hudes\"m\n\x0b\x44imAndSteps\x12\x35\n\x0e\x64ims_and_steps\x18\x01 \x03(\x0b\x32\x1d.hudes.DimAndSteps.DimAndStep\x1a\'\n\nDimAndStep\x12\x0b\n\x03\x64im\x18\x01 \x02(\x05\x12\x0c\n\x04step\x18\x02 \x02(\x02\"\xc9\x01\n\x07\x43ontrol\x12!\n\x04type\x18\x01 \x02(\x0e\x32\x13.hudes.Control.Type\x12+\n\x0e\x64ims_and_steps\x18\xc8\x01 \x01(\x0b\x32\x12.hudes.DimAndSteps\"n\n\x04Type\x12\x10\n\x0c\x43ONTROL_DIMS\x10\x00\x12\x12\n\x0e\x43ONTROL_RESULT\x10\x01\x12\x16\n\x12\x43ONTROL_NEXT_BATCH\x10\x65\x12\x15\n\x11\x43ONTROL_NEXT_DIMS\x10\x66\x12\x11\n\x0c\x43ONTROL_QUIT\x10\x85\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hudes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DIMANDSTEPS']._serialized_start=22
  _globals['_DIMANDSTEPS']._serialized_end=131
  _globals['_DIMANDSTEPS_DIMANDSTEP']._serialized_start=92
  _globals['_DIMANDSTEPS_DIMANDSTEP']._serialized_end=131
  _globals['_CONTROL']._serialized_start=134
  _globals['_CONTROL']._serialized_end=335
  _globals['_CONTROL_TYPE']._serialized_start=225
  _globals['_CONTROL_TYPE']._serialized_end=335
# @@protoc_insertion_point(module_scope)
